// ─── Mock Products ────────────────────────────────────────────────────────────
export const MOCK_PRODUCTS = [
  {
    _id: 'p1',
    name: 'Wireless Noise-Cancelling Headphones',
    slug: 'wireless-noise-cancelling-headphones',
    description: 'Premium over-ear headphones with active noise cancellation, 30-hour battery life, and foldable design. Perfect for travel and daily commutes. Connects via Bluetooth 5.2 for stable wireless audio.',
    price: 89.99,
    originalPrice: 129.99,
    category: 'Electronics',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=700',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=700',
    ],
    brand: 'SoundWave',
    stock: 45,
    rating: 4.3,
    numReviews: 128,
    isFeatured: true,
    isNewArrival: false,
    tags: ['headphones', 'audio', 'wireless', 'noise-cancelling'],
    reviews: [
      { _id: 'r1', name: 'Alex M.', rating: 5, comment: 'Incredible sound quality for the price. The noise cancellation actually works.', createdAt: '2024-11-01' },
      { _id: 'r2', name: 'Sarah K.', rating: 4, comment: 'Very comfortable for long sessions. Battery lasts all day easily.', createdAt: '2024-10-22' },
    ],
    createdAt: '2024-09-01',
  },
  {
    _id: 'p2',
    name: 'Classic Cotton Crew Neck Tee',
    slug: 'classic-cotton-crew-neck-tee',
    description: 'Everyday essential made from 100% organic cotton. Relaxed fit, pre-shrunk, and available in 12 colors. Washes well, keeps its shape. A wardrobe staple.',
    price: 24.99,
    originalPrice: null,
    category: 'Clothing',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=700',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=700',
    ],
    brand: 'BasicsLab',
    stock: 200,
    rating: 4.6,
    numReviews: 89,
    isFeatured: true,
    isNewArrival: true,
    tags: ['tshirt', 'cotton', 'basics', 'clothing'],
    reviews: [
      { _id: 'r3', name: 'Jamie L.', rating: 5, comment: 'Finally a basic tee that fits right and doesn\'t shrink. Ordered three.', createdAt: '2024-11-10' },
    ],
    createdAt: '2024-10-15',
  },
  {
    _id: 'p3',
    name: 'Ceramic Pour-Over Coffee Set',
    slug: 'ceramic-pour-over-coffee-set',
    description: 'Handcrafted ceramic dripper and server. Makes 2–4 cups. Includes 40 paper filters and a cleaning brush. Makes genuinely better coffee than most machines.',
    price: 44.50,
    originalPrice: 59.99,
    category: 'Home & Garden',
    images: [
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=700',
    ],
    brand: 'BrewCraft',
    stock: 30,
    rating: 4.8,
    numReviews: 54,
    isFeatured: true,
    isNewArrival: false,
    tags: ['coffee', 'ceramic', 'kitchen', 'brewing'],
    reviews: [
      { _id: 'r4', name: 'Tom R.', rating: 5, comment: 'Changed my morning routine completely. Coffee tastes noticeably better.', createdAt: '2024-10-05' },
      { _id: 'r5', name: 'Mia C.', rating: 4, comment: 'Beautiful design, brews great. Took a bit to learn the right technique.', createdAt: '2024-09-28' },
    ],
    createdAt: '2024-08-20',
  },
  {
    _id: 'p4',
    name: 'Yoga Mat — Non-Slip 6mm',
    slug: 'yoga-mat-non-slip-6mm',
    description: 'Eco-friendly TPE yoga mat with alignment lines printed on both sides. Non-slip texture, 6mm cushioning. Includes a carry strap. Good for yoga, pilates, and stretching.',
    price: 38.00,
    originalPrice: null,
    category: 'Sports',
    images: [
      'https://images.unsplash.com/photo-1601925228005-55e05d4c5c93?w=700',
    ],
    brand: 'FlexFlow',
    stock: 75,
    rating: 4.4,
    numReviews: 212,
    isFeatured: false,
    isNewArrival: true,
    tags: ['yoga', 'fitness', 'mat', 'exercise'],
    reviews: [],
    createdAt: '2024-11-01',
  },
  {
    _id: 'p5',
    name: 'The Design of Everyday Things',
    slug: 'the-design-of-everyday-things',
    description: 'Don Norman\'s landmark book on human-centered design. Revised and expanded edition. Essential reading for product designers, developers, and anyone curious about why things work the way they do.',
    price: 17.99,
    originalPrice: 22.00,
    category: 'Books',
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=700',
    ],
    brand: 'Basic Books',
    stock: 120,
    rating: 4.7,
    numReviews: 340,
    isFeatured: false,
    isNewArrival: false,
    tags: ['design', 'ux', 'book', 'nonfiction'],
    reviews: [],
    createdAt: '2024-07-01',
  },
  {
    _id: 'p6',
    name: 'Mechanical Keyboard — TKL Brown Switch',
    slug: 'mechanical-keyboard-tkl-brown-switch',
    description: 'Tenkeyless layout with Cherry MX Brown switches — tactile bump, no click. PBT keycaps, USB-C detachable cable, and white backlight. Solid build, not a toy.',
    price: 74.99,
    originalPrice: 99.99,
    category: 'Electronics',
    images: [
      'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=700',
    ],
    brand: 'KeyForge',
    stock: 18,
    rating: 4.5,
    numReviews: 67,
    isFeatured: true,
    isNewArrival: false,
    tags: ['keyboard', 'mechanical', 'typing', 'desk'],
    reviews: [],
    createdAt: '2024-09-10',
  },
  {
    _id: 'p7',
    name: 'Linen Jogger Pants',
    slug: 'linen-jogger-pants',
    description: 'Relaxed linen-blend joggers with elastic waistband, drawstring, and two side pockets. Lightweight and breathable — great for warm weather or working from home.',
    price: 49.99,
    originalPrice: null,
    category: 'Clothing',
    images: [
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=700',
    ],
    brand: 'BasicsLab',
    stock: 60,
    rating: 4.2,
    numReviews: 43,
    isFeatured: false,
    isNewArrival: true,
    tags: ['pants', 'linen', 'casual', 'summer'],
    reviews: [],
    createdAt: '2024-11-05',
  },
  {
    _id: 'p8',
    name: 'Stainless Steel Water Bottle 32oz',
    slug: 'stainless-steel-water-bottle-32oz',
    description: 'Double-wall vacuum insulated. Keeps drinks cold 24hr, hot 12hr. Leak-proof lid. BPA-free. Wide mouth fits ice cubes. Actually fits in most car cupholders.',
    price: 29.95,
    originalPrice: null,
    category: 'Sports',
    images: [
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=700',
    ],
    brand: 'HydroKeep',
    stock: 150,
    rating: 4.6,
    numReviews: 891,
    isFeatured: false,
    isNewArrival: false,
    tags: ['bottle', 'hydration', 'insulated', 'gym'],
    reviews: [],
    createdAt: '2024-06-01',
  },
  {
    _id: 'p9',
    name: 'Indoor Plant Grow Light',
    slug: 'indoor-plant-grow-light',
    description: 'Full-spectrum LED grow light with built-in timer (3/9/12hr). Flexible gooseneck, 3 light modes, 10 brightness levels. USB powered. Works great for succulents and herbs.',
    price: 35.00,
    originalPrice: 45.00,
    category: 'Home & Garden',
    images: [
      'https://images.unsplash.com/photo-1585437308608-4de8e4e0ecf3?w=700',
    ],
    brand: 'GrowEasy',
    stock: 40,
    rating: 4.1,
    numReviews: 29,
    isFeatured: false,
    isNewArrival: true,
    tags: ['plants', 'led', 'garden', 'indoor'],
    reviews: [],
    createdAt: '2024-10-20',
  },
  {
    _id: 'p10',
    name: 'Minimalist Leather Wallet',
    slug: 'minimalist-leather-wallet',
    description: 'Slim bifold in full-grain vegetable-tanned leather. Holds 6 cards + cash slot. No flashy branding. Gets better looking with age.',
    price: 42.00,
    originalPrice: null,
    category: 'Clothing',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=700',
    ],
    brand: 'CraftGoods',
    stock: 55,
    rating: 4.9,
    numReviews: 176,
    isFeatured: true,
    isNewArrival: false,
    tags: ['wallet', 'leather', 'accessories', 'minimalist'],
    reviews: [],
    createdAt: '2024-08-01',
  },
  {
    _id: 'p11',
    name: 'USB-C Hub 7-in-1',
    slug: 'usb-c-hub-7-in-1',
    description: 'HDMI 4K@60Hz, 3× USB-A 3.0, SD + microSD reader, 100W pass-through charging. Compact aluminum housing. Works with MacBooks, iPads, and most USB-C laptops.',
    price: 39.99,
    originalPrice: 54.99,
    category: 'Electronics',
    images: [
      'https://images.unsplash.com/photo-1625799522513-f2a6a8a3f2c1?w=700',
    ],
    brand: 'ConnectPro',
    stock: 88,
    rating: 4.3,
    numReviews: 215,
    isFeatured: false,
    isNewArrival: false,
    tags: ['usb-c', 'hub', 'laptop', 'accessories'],
    reviews: [],
    createdAt: '2024-07-15',
  },
  {
    _id: 'p12',
    name: 'Wooden Desk Organizer Set',
    slug: 'wooden-desk-organizer-set',
    description: 'Bamboo set: letter tray, pen cup, phone stand, and cable clip. Fits most desks. No tools needed for assembly. Naturally antibacterial.',
    price: 32.50,
    originalPrice: null,
    category: 'Home & Garden',
    images: [
      'https://images.unsplash.com/photo-1593642634443-44adaa06623a?w=700',
    ],
    brand: 'DeskNest',
    stock: 33,
    rating: 4.4,
    numReviews: 61,
    isFeatured: false,
    isNewArrival: true,
    tags: ['desk', 'organizer', 'bamboo', 'office'],
    reviews: [],
    createdAt: '2024-10-28',
  },
  {
    _id: 'p13',
    name: 'Running Shoes — Lightweight',
    slug: 'running-shoes-lightweight',
    description: 'Breathable mesh upper with cushioned midsole. Suitable for road running, gym, and casual wear. Available in sizes 6–14.',
    price: 64.99,
    originalPrice: 89.99,
    category: 'Sports',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=700',
    ],
    brand: 'PaceUp',
    stock: 0,
    rating: 4.2,
    numReviews: 98,
    isFeatured: false,
    isNewArrival: false,
    tags: ['shoes', 'running', 'sports', 'footwear'],
    reviews: [],
    createdAt: '2024-07-20',
  },
  {
    _id: 'p14',
    name: 'Scented Soy Candle — Cedar & Smoke',
    slug: 'scented-soy-candle-cedar-smoke',
    description: 'Hand-poured 8oz soy wax candle with a cotton wick. Cedar, vetiver, and light smoke. Burns for ~45 hours. Made in small batches in Portland, OR.',
    price: 22.00,
    originalPrice: null,
    category: 'Home & Garden',
    images: [
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=700',
    ],
    brand: 'WickWorks',
    stock: 85,
    rating: 4.7,
    numReviews: 133,
    isFeatured: true,
    isNewArrival: true,
    tags: ['candle', 'soy', 'home', 'scented'],
    reviews: [],
    createdAt: '2024-11-12',
  },
  {
    _id: 'p15',
    name: 'Portable Bluetooth Speaker',
    slug: 'portable-bluetooth-speaker',
    description: '360° sound, IPX7 waterproof, 20-hour battery. Pair two for stereo mode. Surprisingly loud for its size.',
    price: 54.99,
    originalPrice: 69.99,
    category: 'Electronics',
    images: [
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=700',
    ],
    brand: 'SoundWave',
    stock: 22,
    rating: 4.4,
    numReviews: 187,
    isFeatured: false,
    isNewArrival: true,
    tags: ['speaker', 'bluetooth', 'audio', 'portable'],
    reviews: [],
    createdAt: '2024-11-08',
  },
]

// ─── Mock Users ───────────────────────────────────────────────────────────────
export const MOCK_USERS = [
  { _id: 'u1', name: 'Jane Doe', email: 'jane@example.com', password: 'user123', isAdmin: false, wishlist: ['p1', 'p3'] },
  { _id: 'u2', name: 'Admin User', email: 'admin@shopforge.com', password: 'admin123', isAdmin: true, wishlist: [] },
]

// ─── Mock Orders ──────────────────────────────────────────────────────────────
export const MOCK_ORDERS = [
  {
    _id: 'ord_a1b2c3d4',
    user: { _id: 'u1', name: 'Jane Doe', email: 'jane@example.com' },
    items: [
      { product: 'p1', name: 'Wireless Noise-Cancelling Headphones', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=700', price: 89.99, quantity: 1 },
      { product: 'p3', name: 'Ceramic Pour-Over Coffee Set', image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=700', price: 44.50, quantity: 1 },
    ],
    shippingAddress: { fullName: 'Jane Doe', street: '123 Main St', city: 'Portland', state: 'OR', zip: '97201', country: 'US' },
    paymentMethod: 'card',
    subtotal: 134.49,
    shippingPrice: 0,
    taxPrice: 10.76,
    totalPrice: 145.25,
    status: 'delivered',
    isPaid: true,
    paidAt: '2024-10-20',
    isDelivered: true,
    deliveredAt: '2024-10-25',
    createdAt: '2024-10-19',
  },
  {
    _id: 'ord_e5f6g7h8',
    user: { _id: 'u1', name: 'Jane Doe', email: 'jane@example.com' },
    items: [
      { product: 'p6', name: 'Mechanical Keyboard — TKL Brown Switch', image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=700', price: 74.99, quantity: 1 },
    ],
    shippingAddress: { fullName: 'Jane Doe', street: '123 Main St', city: 'Portland', state: 'OR', zip: '97201', country: 'US' },
    paymentMethod: 'paypal',
    subtotal: 74.99,
    shippingPrice: 5.99,
    taxPrice: 6.00,
    totalPrice: 86.98,
    status: 'shipped',
    isPaid: true,
    paidAt: '2024-11-10',
    isDelivered: false,
    createdAt: '2024-11-10',
  },
]
